### ISSUE TITLE
[ Feature request ] 메인 홈 화면 UI 개발

### ISSUE THREAD

**Issue by skrud9704** [depromeet/LinkZupZup-AOS#1]
개요
-------------------------------------
개인 레포지토리에서 작업하던 Main UI 내용을 프로젝트와 합치려고 합니다.

작업사항
-------------------------------------
 - Main UI 적용
 - Bottom Sheet 적용

**Comment by Minsu-Lee** [comment]
@skrud9704 나경님, 이 이슈는 어느 브런치에서 작업하셨을가요?

**Comment by skrud9704** [comment]
@Minsu-Lee 이거 Main_UI_1 브랜치에서 작업했습니다!

**Comment by Minsu-Lee** [comment]
@skrud9704 git pull을 해도 해당 브랜치가 확인되지 않아서요.
시간 되실때 카톡한번주세요~

**Comment by Minsu-Lee** [comment]
@skrud9704 프로젝트를 지우고 다시 불러오니 나오네요
문제가 많네...

**Comment by skrud9704** [comment]
@Minsu-Lee 학교에서 작업하다 git에 다른 사용자 명이 남은 상태에서 push를 했네요. 
push reset 후 덮어써놓았는데, 현재 브랜치에서 문제가 없는지 확인부탁드립니다!

**Comment by Minsu-Lee** [comment]
@skrud9704 깃 로그에 다른 사용자명이 남아 있진 않네요

**Comment by Minsu-Lee** [comment]
완벽하게 UI를 끝낸건 아니지만 향후 기능개발 진행시 다듬기로 하고 이번 이슈는 종료합니다.
