### ISSUE TITLE
[ Feature request ] Link WebView UI

### ISSUE THREAD

**Issue by skrud9704** [depromeet/LinkZupZup-AOS#18]
개요
-------------------------------------
링크 웹뷰 페이지 UI 개발

작업사항
-------------------------------------
 - WebView Top bar
 - Jetpack Compose WebView
 - Popup(Dialog Custom)

**Comment by Minsu-Lee** [comment]
@skrud9704 나경님~ 웹뷰 설정들 진행안하면 특정페이지에서 웹이 안나올수 있어요
아래는 이전에 다른 프로젝트에서 사용하던 설정인데, 참고하셔서 반영해주세요~
현재 링줍의 웹뷰는 일반브라우저 처럼 돌아다닐 수 있으니 잘판단해서 반영해주세요~

// WebView.settings
settings.run {
    // 자바스크립트 사용 허용
    javaScriptEnabled = true
    // 자바스크립트에서 새창 실 행 허용
    javaScriptCanOpenWindowsAutomatically = true
    // 파일 url 호출 권한
    allowUniversalAccessFromFileURLs = true
    // 웹에서 localStorage처럼 클라이언트에 데이터를 저장하는 권한
    domStorageEnabled = true
    // 메타 태그 허용
    loadWithOverviewMode = true
}

**Comment by skrud9704** [comment]
해당 이슈는 완료됐으므로 닫겠습니다.
