### ISSUE TITLE
[ Feature request ] MyDonut 내도넛히스토리 추가화면 - 포인트/도넛 기준 안내

### ISSUE THREAD

**Issue by skrud9704** [depromeet/LinkZupZup-AOS#23]
개요
-------------------------------------
추가된 화면 작업
내 도넛 히스토리에서 포인트와 도넛의 기준안내 화면

작업사항
-------------------------------------
 - 전체 바디를 Scaffold에서 ModalBottomSheetLayout로 변경해 적용
 - 추가된 화면 Sheet로 구성

**Comment by Minsu-Lee** [comment]
@skrud9704 "포인트와 도넛의 기준은?" 이부분은 
다른 아이템들과 함께 스크롤되어 지나가야 하지 않을가 싶어요
나경님 의견은 어떤가요
근데 어떻게 LazyVerticalGrid에 포함시키지

**Comment by skrud9704** [comment]
@Minsu-Lee 디자이너 분들이랑 이야기해보고 그렇게 해달라하면 이것도 MainContentData 처럼 Int값으로 타입 구분(item인가 header인가)해서 하면 될 거 같아요. 
Lazy Vertical Grid에 span 같은 기능이 있을 것 같은데 찾아볼게요~

**Comment by Minsu-Lee** [comment]
포인트와 도넛의 기준 바텀시트가 추가되었습니다. 진행 부탁드려요 ㅎㅎ

**Comment by skrud9704** [comment]
해당 이슈 완료하여 닫겠습니다.
