### ISSUE TITLE
[ Feature request ] 온보딩 UI 개발

### ISSUE THREAD

**Issue by skrud9704** [depromeet/LinkZupZup-AOS#33]
개요
-------------------------------------
온보딩 화면 개발

작업사항
-------------------------------------
 - 온보딩 UI
 - 푸시 애니메이션

**Comment by skrud9704** [comment]
온보딩 UI까지 완료됐습니다.

**Comment by Minsu-Lee** [comment]
굳, 애니메이션은 추후 새로운 이슈 열어서 진행하시져
고생하셨습니다.
